repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_providers_lock
      # - id: terraform_wrapper_module_for_each
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - --args=--only=terraform_deprecated_interpolation
          - --args=--only=terraform_deprecated_index
          - --args=--only=terraform_unused_declarations
          - --args=--only=terraform_comment_syntax
          - --args=--only=terraform_documented_outputs
          - --args=--only=terraform_documented_variables
          - --args=--only=terraform_typed_variables
          - --args=--only=terraform_module_pinned_source
          - --args=--only=terraform_naming_convention
          - --args=--only=terraform_required_version
          - --args=--only=terraform_required_providers
          - --args=--only=terraform_standard_module_structure
          - --args=--only=terraform_workspace_remote
      - id: terraform_trivy
      - id: terrascan
      - id: checkov
        args:
          - --framework=terraform
          - --skip-check=CKV_AWS_8
      - id: infracost_breakdown
        args:
          - --args=--path=./examples/basic
          - --hook-config=".totalHourltCost|tonumber > 0.01"
          - --hook-config=".totalMonthlyCost|tonumber > 1"
      - id: infracost_breakdown
        args:
          - --args=--path=./examples/basic
          - --hook-config=".diffTotalHourlyCost|tonumber > 0.01"
          - --hook-config=".diffTotalMonthlyCost|tonumber > 1"
          - --hook-config='.currency == "USD"'
        verbose: true # Always show the output of infracost
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace