name: Terraform CI
run-name: Build run by ${{ github.actor }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'VERSION'
      - 'CHANGELOG.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - '*.sh'
      - '*.txt'
      - '*.json'
      - '.gitignore'
      - '.editorconfig'
      - '.pre-commit-config.yaml'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  terraform-ci:
    name: CI
    if: github.ref != 'refs/heads/main'
    uses: subhamay-bhattacharyya-gha/tf-ci-reusable-wf/.github/workflows/ci.yaml@feature/GHA-0009-add-condition-for-feature
    with:
      environment: "ci"
      terraform-dir: "tf"
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      infracost-api-key: ${{ secrets.INFRACOST_API_KEY }}
      infracost-gist-id: ${{ secrets.INFRACOST_GIST_ID }}

  create-release:
    name: Create Release
    if: github.ref == 'refs/heads/main'
    needs: terraform-ci
    uses: subhamay-bhattacharyya-gha/tf-release-wf/.github/workflows/create-release.yaml@feature/GHA-0002-initial-release
    with:
      environment: "ci"
      terraform-dir: "tf"
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      infracost-api-key: ${{ secrets.INFRACOST_API_KEY }}
      infracost-gist-id: ${{ secrets.INFRACOST_GIST_ID }}
