name: Terraform Destroy
run-name: Terraform Destroy - ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (e.g., devl, test, prod)"
        required: true
        type: environment
        default: devl


jobs:
  apply:
    name: 🚧 Run Terraform Destroy
    uses: subhamay-bhattacharyya-gha/tf-apply-wf/.github/workflows/terraform-destroy.yaml@main
    with:
      environment: ${{ inputs.environment }}
      terraform-dir: ${{ inputs.terraform-dir }}
      tf-vars-file: ${{ inputs.tf-vars-file }}
      ci-pipeline: false
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      infracost-api-key: ${{ secrets.INFRACOST_API_KEY }}
      infracost-gist-id: ${{ secrets.INFRACOST_GIST_ID }}